### ISSUE TITLE
Working on python2.7 on windows but not on 3.65

### ISSUE THREAD

**Issue by lordbeerus0505** [openalpr/cloudapi#19]
Is version 3.65 supported? I keep the error -
AttributeError: 'bytes' object has no attribute 'swagger_types'
Whats the fix to this? On 2.7.15 it works perfectly
